ekf_node:
  ros__parameters:
    initial_position: [0.0, 0.0, 0.0]
    initial_attitude: [1.0, 0.0, 0.0, 0.0]
    imu_topic: "/imu/data"
    gnss_topic: "/gnss/data"
    kf_config.init_att_unc: 0.0174533  # 1.0 deg in radians
    kf_config.init_vel_unc: 0.1
    kf_config.init_pos_unc: 10.0
    kf_config.init_b_a_unc: 0.00980665
    kf_config.init_b_g_unc: 4.84814e-6
    kf_config.gyro_noise_PSD: 1.21847e-9
    kf_config.accel_noise_PSD: 3.844e-6
    kf_config.accel_bias_PSD: 1.0E-7
    kf_config.gyro_bias_PSD: 2.0E-12
