ros2_lc_ins_gnss_ecef:
  ros__parameters:
    imu_topic: "/imu_dirty/data"
    gnss_topic: "/gnss/fix"
    out_pose_topic: "/nav_sol/pose"
    write_log: false
    log_path: "/home/tommaso/myLibs/IntNavLib/apps/ros2_lc_ins_gnss_ecef/results/Profile_3_lc_ins_gnss_ecef_ros2.csv"
    init_lla : [50.425,-3.595,10010.0] # deg, m
    init_v_eb_n: [0.0,199.998794,0.0] # m/s
    init_rpy_b_n: [0.0,0.0,90.01] # deg
    kf_config.init_att_unc: 0.0174533 # rad
    kf_config.init_vel_unc: 0.1 # m/s
    kf_config.init_pos_unc: 10.0 # m
    kf_config.init_b_a_unc: 0.0 # m/s^2
    kf_config.init_b_g_unc: 0.0 # rad/sec
    kf_config.accel_noise_PSD: 3.8468153689e-06 # m^2 s^-3
    kf_config.accel_bias_PSD: 1.0E-7 # m^2 s^-5
    kf_config.gyro_noise_PSD: 3.3846379976520888e-11 # rad^2/s
    kf_config.gyro_bias_PSD: 2.0E-12 # rad^2 s^-3
