ros2_lc_ins_gnss_ecef:
  ros__parameters:
    imu_topic: "/imu_dirty/data"
    gnss_topic: "/gnss/fix"
    out_pose_topic: "/nav_sol/pose"
    write_log: false
    log_path: "/home/tommaso/myLibs/IntNavLib/apps/ros2_lc_ins_gnss_ecef/results/Profile_3_lc_ins_gnss_ecef_ros2.csv"
    init_lla : [50.425,-3.595805199,10000.0] # deg, m
    init_v_eb_n: [0.0,199.998794,0.0] # m/s
    init_rpy_b_n: [0.0,0.0,90.01] # deg
    kf_config.init_att_unc: 0.0174533 # rad, deg_to_rad * 1.0;
    kf_config.init_vel_unc: 0.1 # m/s
    kf_config.init_pos_unc: 10.0 # m
    kf_config.init_b_a_unc: 0.00980665 # m/s^2, 1000.0 * micro_g_to_meters_per_second_squared
    kf_config.init_b_g_unc: 4.8481368e-05 # rad/sec,  10.0 * deg_to_rad / 3600.0
    kf_config.gyro_noise_PSD: 3.3846379976520888e-11 # rad^2/s, pow(0.02 * deg_to_rad / 60.0, 2.0)
    kf_config.accel_noise_PSD: 3.8468153689e-06 # m^2 s^-3, pow(200.0 * micro_g_to_meters_per_second_squared, 2.0);
    kf_config.accel_bias_PSD: 1.0E-7 # m^2 s^-5
    kf_config.gyro_bias_PSD: 2.0E-12 # rad^2 s^-3
